apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=2.1
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: wordpress-pv-2  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//gffa-dc-1/share"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
